The Scenario: You are given three separate datasets: "Customer Profiles" (age, region, subscription tier), "Product Catalog" (category, weight, unit price), and "Order Transactions" (who bought what, when, and delivery times).

In [11]:
import pandas as pd

df1 = pd.read_csv("customers - customers.csv")
df2 = pd.read_csv("orders_feb - orders_feb.csv")
df3 = pd.read_csv("orders_jan - orders_jan.csv")
df4 = pd.read_csv("products - products.csv")
[df1, df2, df3, df4]

[    Customer_ID  Age Region Subscription_Tier
 0         C0001   56  North             Basic
 1         C0002   69  South              Plus
 2         C0003   46  North              Plus
 3         C0004   32  South             Basic
 4         C0005   60   East           Premium
 ..          ...  ...    ...               ...
 995       C0996   37  North             Basic
 996       C0997   41  North              Plus
 997       C0998   22  North           Premium
 998       C0999   51   East             Basic
 999       C1000   23   West             Basic

 [1000 rows x 4 columns],
     Transaction_ID cust_ID Product_ID  Quantity  Order_Date  Delivery_Days  \
 0           T01001   C0942      P0525         5  2024-02-13              6
 1           T01002   C0675      P0908         3  2024-02-08              7
 2           T01003   C0685      P0255         4  2024-02-19              3
 3           T01004   C0141      P0085         4  2024-02-05              5
 4           T01005   C0138      P0458         2  2024-02-02              7
 ..             ...     ...        ...       ...         ...            ...
 995         T01996   C0637      P0623         3  2024-02-19              3
 996         T01997   C0716      P0210         3  2024-02-09              4
 997         T01998   C0573      P0513         1  2024-02-09              1
 998         T01999   C0762      P0058         3  2024-02-13              2
 999         T02000   C0810      P0093         4  2024-02-06              5

     Warehouse_Route_ID
 0                WH-D9
 1                WH-A1
 2                WH-A3
 3                WH-C8
 4                WH-E8
 ..                 ...
 995              WH-C2
 996              WH-A8
 997              WH-B4
 998              WH-C9
 999              WH-B6

 [1000 rows x 7 columns],
     Transaction_ID cust_ID Product_ID  Quantity  Order_Date  Delivery_Days  \
 0           T00001   C0546      P0146         4  2024-01-26              2
 1           T00002   C0609      P0938         1  2024-01-22              6
 2           T00003   C0169      P0057         3  2024-01-07              6
 3           T00004   C0681      P0723         1  2024-01-10              1
 4           T00005   C0663      P0780         3  2024-01-28              1
 ..             ...     ...        ...       ...         ...            ...
 995         T00996   C0196      P0282         3  2024-01-19              7
 996         T00997   C0307      P0133         3  2024-01-24              2
 997         T00998   C0664      P0534         5  2024-01-15              3
 998         T00999   C0014      P0975         5  2024-01-26              5
 999         T01000   C0837      P0269         1  2024-01-07              7

     Warehouse_Route_ID
 0                WH-A1
 1                WH-C4
 2                WH-B3
 3                WH-A9
 4                WH-A7
 ..                 ...
 995              WH-B2
 996              WH-D6
 997              WH-C9
 998              WH-C3
 999              WH-B9

 [1000 rows x 7 columns],
     Product_ID Product_Category  Weight_kg  Unit_Price
 0        P0001    Home & Garden       3.39      180.56
 1        P0002           Sports       0.68      277.58
 2        P0003      Electronics       0.64      204.59
 3        P0004         Clothing       2.71      417.65
 4        P0005           Sports      13.01      408.26
 ..         ...              ...        ...         ...
 995      P0996             Toys       1.83      193.90
 996      P0997           Sports       9.23      388.74
 997      P0998           Sports      14.08      174.58
 998      P0999         Clothing       9.96      315.70
 999      P1000    Home & Garden       1.24      100.05

 [1000 rows x 4 columns]]

Combining Datasets: You must use pd.concat() to stitch together the order transactions from "January" and "February". Then, use pd.merge() to join the combined 'Order Transactions' table with the 'Product Catalog' table so you know the category and price of the item purchased, acting like a SQL left join.

In [30]:
combined_df2_df3 = pd.concat([df2, df3], ignore_index=True)
#combined_df2_df3

df = pd.merge(combined_df2_df3, df4, on="Product_ID", how='left')
df

,Transaction_ID,cust_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Warehouse_Route_ID,Product_Category,Weight_kg,Unit_Price
0,T01001,C0942,P0525,5,2024-02-13,6,WH-D9,Home & Garden,5.59,35.71
1,T01002,C0675,P0908,3,2024-02-08,7,WH-A1,Sports,4.39,128.06
2,T01003,C0685,P0255,4,2024-02-19,3,WH-A3,Sports,9.60,284.14
3,T01004,C0141,P0085,4,2024-02-05,5,WH-C8,Electronics,4.05,379.86
4,T01005,C0138,P0458,2,2024-02-02,7,WH-E8,Toys,0.22,438.19
...,...,...,...,...,...,...,...,...,...,...
1995,T00996,C0196,P0282,3,2024-01-19,7,WH-B2,Electronics,11.09,165.15
1996,T00997,C0307,P0133,3,2024-01-24,2,WH-D6,Sports,10.80,172.04
1997,T00998,C0664,P0534,5,2024-01-15,3,WH-C9,Electronics,10.04,26.81
1998,T00999,C0014,P0975,5,2024-01-26,5,WH-C3,Toys,5.78,399.24
1999,T01000,C0837,P0269,1,2024-01-07,7,WH-B9,Electronics,11.02,397.13

Modifying DataFrames: You create a new calculated column called Total_Revenue by multiplying the Quantity column by the Unit_Price column. Use .drop() to remove redundant warehouse routing IDs, and use .rename() to fix inconsistently capitalized columns (e.g., changing cust_ID to Customer_ID).

In [31]:
df['Total_Revenue'] = df['Quantity'] * df['Unit_Price']

df = df.drop(columns=['Warehouse_Route_ID'])

df = df.rename(columns={'cust_ID': 'Customer_ID'})
df

,Transaction_ID,Customer_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Product_Category,Weight_kg,Unit_Price,Total_Revenue
0,T01001,C0942,P0525,5,2024-02-13,6,Home & Garden,5.59,35.71,178.55
1,T01002,C0675,P0908,3,2024-02-08,7,Sports,4.39,128.06,384.18
2,T01003,C0685,P0255,4,2024-02-19,3,Sports,9.60,284.14,1136.56
3,T01004,C0141,P0085,4,2024-02-05,5,Electronics,4.05,379.86,1519.44
4,T01005,C0138,P0458,2,2024-02-02,7,Toys,0.22,438.19,876.38
...,...,...,...,...,...,...,...,...,...,...
1995,T00996,C0196,P0282,3,2024-01-19,7,Electronics,11.09,165.15,495.45
1996,T00997,C0307,P0133,3,2024-01-24,2,Sports,10.80,172.04,516.12
1997,T00998,C0664,P0534,5,2024-01-15,3,Electronics,10.04,26.81,134.05
1998,T00999,C0014,P0975,5,2024-01-26,5,Toys,5.78,399.24,1996.20
1999,T01000,C0837,P0269,1,2024-01-07,7,Electronics,11.02,397.13,397.13

Applying Functions: You write a custom function (or use a lambda) and apply it via .apply() to categorize the Delivery_Days column into delivery performance buckets: "Early" (1-2 days), "On-Time" (3-4 days), or "Delayed" (5+ days).

In [32]:
df['Delivery_Status'] = df['Delivery_Days'].apply(
    lambda x: 'Early' if x <= 2 
    else 'On-Time' if x <= 4 
    else 'Delayed'
)
df

,Transaction_ID,Customer_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Product_Category,Weight_kg,Unit_Price,Total_Revenue,Delivery_Status
0,T01001,C0942,P0525,5,2024-02-13,6,Home & Garden,5.59,35.71,178.55,Delayed
1,T01002,C0675,P0908,3,2024-02-08,7,Sports,4.39,128.06,384.18,Delayed
2,T01003,C0685,P0255,4,2024-02-19,3,Sports,9.60,284.14,1136.56,On-Time
3,T01004,C0141,P0085,4,2024-02-05,5,Electronics,4.05,379.86,1519.44,Delayed
4,T01005,C0138,P0458,2,2024-02-02,7,Toys,0.22,438.19,876.38,Delayed
...,...,...,...,...,...,...,...,...,...,...,...
1995,T00996,C0196,P0282,3,2024-01-19,7,Electronics,11.09,165.15,495.45,Delayed
1996,T00997,C0307,P0133,3,2024-01-24,2,Sports,10.80,172.04,516.12,Early
1997,T00998,C0664,P0534,5,2024-01-15,3,Electronics,10.04,26.81,134.05,On-Time
1998,T00999,C0014,P0975,5,2024-01-26,5,Toys,5.78,399.24,1996.20,Delayed
1999,T01000,C0837,P0269,1,2024-01-07,7,Electronics,11.02,397.13,397.13,Delayed

Grouping and Aggregation: Using .groupby(), you group the data by Product_Category and use .agg() to find the total revenue generated, the average delivery days, and the unique count of Customer_IDs who purchased from that category.

In [33]:
summary = df.groupby('Product_Category').agg({
    'Total_Revenue': 'sum',
    'Delivery_Days': 'mean',
    'Customer_ID': 'nunique'
})
summary

                  Total_Revenue  Delivery_Days  Customer_ID
Product_Category
Clothing              236216.30       4.005764          289
Electronics           291529.29       3.960688          333
Home & Garden         318433.12       4.009324          342
Sports                311298.28       3.847255          346
Toys                  300972.12       3.871859          316

Reshaping and Pivoting: Finally, you use pd.pivot_table() to create a business-reporting matrix showing "Customer Region" as rows, "Delivery Performance" (Early/On-Time/Delayed) as columns, and the "Total Revenue" as the values.

In [34]:
df = pd.merge(df, df1, on="Customer_ID", how='left')
pivot_table = pd.pivot_table(
    df,
    index='Region',
    columns='Delivery_Status',
    values='Total_Revenue',
    aggfunc='sum'
)

pivot_table

Delivery_Status    Delayed      Early    On-Time
Region
East             165532.82   91495.83  102829.30
North            168913.17  115843.80  125378.86
South            157531.94  112139.58  102640.26
West             129061.42  111503.35   75578.78